# Generated by Django 5.1.6 on 2025-12-18 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_course_course_id_alter_course_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcceptanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, verbose_name='学号')),
                ('acceptance_level', models.IntegerField(help_text='0-100的数值', verbose_name='接受度水平')),
                ('attention_level', models.IntegerField(help_text='0-100的数值', verbose_name='注意力水平')),
                ('engagement_score', models.IntegerField(help_text='0-100的数值', verbose_name='参与度评分')),
                ('dominant_expression', models.CharField(max_length=20, verbose_name='主导表情')),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='置信度')),
                ('session_id', models.CharField(max_length=50, verbose_name='会话ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录教师')),
            ],
            options={
                'verbose_name': '学生接受度数据',
                'verbose_name_plural': '学生接受度数据',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student_id', '-timestamp'], name='students_st_student_e0fcde_idx'), models.Index(fields=['session_id'], name='students_st_session_046e74_idx'), models.Index(fields=['timestamp'], name='students_st_timesta_ed920b_idx')],
            },
        ),
    ]
