# Generated by Django 5.1.6 on 2025-12-14 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_alter_course_course_id_alter_course_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模板名称')),
                ('analysis_type', models.CharField(choices=[('academic_performance', '学业表现分析'), ('learning_progress', '学习进度分析'), ('strength_weakness', '优势劣势分析'), ('improvement_suggestions', '改进建议'), ('comprehensive', '综合分析')], max_length=50, verbose_name='分析类型')),
                ('template', models.TextField(verbose_name='提示词模板')),
                ('variables', models.JSONField(help_text='模板中使用的变量列表', verbose_name='变量列表')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '提示词模板',
                'verbose_name_plural': '提示词模板',
                'ordering': ['analysis_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('academic_performance', '学业表现分析'), ('learning_progress', '学习进度分析'), ('strength_weakness', '优势劣势分析'), ('improvement_suggestions', '改进建议'), ('comprehensive', '综合分析')], max_length=50, verbose_name='分析类型')),
                ('title', models.CharField(max_length=200, verbose_name='分析标题')),
                ('status', models.CharField(choices=[('pending', '待分析'), ('processing', '分析中'), ('completed', '已完成'), ('failed', '分析失败')], default='pending', max_length=20, verbose_name='状态')),
                ('input_data', models.JSONField(help_text='用于分析的学生数据', verbose_name='输入数据')),
                ('analysis_result', models.TextField(blank=True, null=True, verbose_name='分析结果')),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='0.00-1.00', max_digits=3, null=True, verbose_name='AI 置信度')),
                ('prompt_template', models.TextField(verbose_name='提示词模板')),
                ('actual_prompt', models.TextField(blank=True, null=True, verbose_name='实际使用的提示词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='分析完成时间')),
                ('analyzed_by', models.CharField(default='DeepSeek AI', max_length=100, verbose_name='分析引擎')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生学情分析',
                'verbose_name_plural': '学生学情分析',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIServiceLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('analysis', '学情分析'), ('suggestion', '建议生成'), ('evaluation', '评估分析')], max_length=20, verbose_name='请求类型')),
                ('request_prompt', models.TextField(verbose_name='请求提示词')),
                ('request_data', models.JSONField(verbose_name='请求数据')),
                ('response_content', models.TextField(blank=True, null=True, verbose_name='响应内容')),
                ('response_time', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='响应时间(秒)')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('timeout', '超时')], max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('student_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_analysis.studentanalysis', verbose_name='关联分析')),
            ],
            options={
                'verbose_name': 'AI 服务日志',
                'verbose_name_plural': 'AI 服务日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
